fix: Fix last check if repo already exist
Signed-off-by: shiipou <shiishii@nocturlab.fr>

diff --git a/clone b/clone
--- a/clone
+++ b/clone
@@ -20,26 +20,32 @@ if [[ $1 =~ $regex ]]; then
     repo=${BASH_REMATCH[5]}
     path="$GIT_HOME/$hostname/$user/$repo"
 
-    # Clone the repo
-    git clone "$url" "$path"
+    if ! ls $path &> /dev/null
+    then
+        git clone "$url" "$path"
 
-    # If the clone was successful, then print a success message
-    if [ $? -eq 0 ]; then
-        echo "Cloned $url"
+        # If the clone was successful, then print a success message
+        if [ $? -eq 0 ]; then
+            echo "Cloned $url"
+        else
+            # If the clone failed, then print an error
+            echo "Error cloning $url"
+            exit
+        fi
     else
-        # If the clone failed, then print an error
-        echo "Error cloning $url"
+        echo "Repo already exists"
     fi
-
     # Check if JQ is installed
     if ! command -v jq &> /dev/null
     then
         echo "If you install jq, then the repo will be added to the list of repos in the VSCode's project manager extension"
         exit
     fi
+
     # adding the repo to the list of repos in /home/shiishii/.config/Code/User/globalStorage/alefragnani.project-manager/projects.json
     # if the repo was not already present
-    if ! grep -q "$path" "$PROJECTS_FILE"; then
+    if ! grep -q "$path" "$PROJECTS_FILE"
+    then
         # Add the repo to the list of repos
         cat "$PROJECTS_FILE" | jq ". += [{\"name\": \"$repo\", \"rootPath\": \"$path\", \"paths\": [], \"tags\": [\"$user\"]}]" > "$PROJECTS_FILE.tmp"
         mv "$PROJECTS_FILE.tmp" "$PROJECTS_FILE"
